### ISSUE TITLE
Sample rate of speech.npy?

### ISSUE THREAD

**Issue by s-ben** [Wramberg/adaptfilt#1]
Not an "issue", per se, but I'm wondering what the sample rate is of the audio used in the example (speech.npy)? I assume I need to know this in order to change the step size parameter ('step') to accommodate a different sample rate?

**Comment by tausen** [comment]
The speech.npy file seems to be sampled at 11.025kHz. And yeah, you'll probably have to tweak the step size for other sample rates. Don't rely on any direct relationship, though - for audio with different characteristics you might get better results with other step sizes. I've found the best approach to be just tweaking the parameter until I'm satisfied with the result :)

If you want to listen to the audio, you can generate a wav file from the numpy array using scipy.io.wavfile:

```
import numpy as np
from scipy.io.wavfile import write

d = np.load("speech.npy")
s = np.int16(d/np.max(np.abs(d))*32767)
write('speech.wav', 11025, s)
```
