### ISSUE TITLE
sample rate for example speech should be included

### ISSUE THREAD

**Issue by aparks5** [Wramberg/adaptfilt#2]
i figured out it was 12khz...after using scipy.io wavwrite with 44.1khz, 16khz, and 8khz. i would preferred to avoid doing that (: thanks

**Comment by tausen** [comment]
Hi @aparks5,

Thanks for the heads-up.

I've added a few comments in the example description and an example of how to store signals in a playable wav format. It's on the v0.3 branch for now, so it should eventually reach master.

**Comment by aparks5** [comment]
Thanks for updating the docs!
