### ISSUE TITLE
Issue while trying to compile with latest python

### ISSUE THREAD

**Issue by kalpana-manickavasagam** [Wramberg/adaptfilt#5]
File "/usr/local/lib/python3.6/dist-packages/adaptfilt/__init__.py", line 41
    print '   LMS: ', lmsres
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('   LMS: ', lmsres)?

**Comment by tausen** [comment]
Yes, this module was written for Python 2 and has not been updated for a while. There is a PR (#3) that fixes this particular detail, but I suspect a few more minor changes are needed to support Python 3.

We will gladly accept a PR, though, so don't hold back :)

**Comment by josephernest** [comment]
Hi @tausen! Congrats for this library! Would you have a Python3 version? Thanks a lot in advance :)

**Comment by tausen** [comment]
Hi @josephernest! Happy to see there's still some interest in this library, despite it being unmaintained for a decade :) 
I've (finally) merged an old v0.3 PR which added Python 3 support (among a few other things) and uploaded it to pypi, so it should work now.
