### ISSUE TITLE
lms not imported from lms

### ISSUE THREAD

**Issue by pallaskoers** [Wramberg/adaptfilt#6]
Hi,

I get the error saying

  File "C:\Users\palla\anaconda3\lib\site-packages\adaptfilt\__init__.py", line 19, in <module>
    from lms import lms

ImportError: cannot import name 'lms' from 'lms' 

how can I fix this?

**Comment by Hongfei-Niu** [comment]
This command may solve the problem.
2to3 <package path> -w

**Comment by tausen** [comment]
Should be fixed in v0.3
